apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: wordpress-development
  labels:
    app: phpmyadmin
    tier: frontend
    env: development
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
    tier: frontend
    env: development
  ports:
    - protocol: TCP
      port: 80
  